Mudança nas permissões de escrita dentro do github actions no nas configurações

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -20,13 +20,17 @@ jobs:
         uses: actions/setup-node@v4
         with:
           node-version: 20
-          cache: 'npm'
 
       - name: Install dependencies
         run: npm install
 
       - name: Build
         run: npm run build
+        env:
+          NODE_ENV: production
+
+      - name: Debug Build
+        run: ls -R dist || echo "Dist not found"
 
       - name: Setup Pages
         uses: actions/configure-pages@v4
